# Generated by Django 3.2 on 2021-04-23 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='title',
            field=models.CharField(default='Untitled Game', max_length=25),
        ),
        migrations.AddField(
            model_name='player',
            name='first_name',
            field=models.CharField(default='First name', max_length=25),
        ),
        migrations.AddField(
            model_name='player',
            name='last_name',
            field=models.CharField(default='Last name', max_length=25),
        ),
    ]
