# Generated by Django 3.2 on 2021-05-18 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20210423_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='recipient',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.player'),
        ),
        migrations.AlterField(
            model_name='player',
            name='first_name',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='player',
            name='last_name',
            field=models.CharField(default='', max_length=25),
        ),
    ]
