# Generated by Django 3.2 on 2021-05-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_alter_player_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='player',
            name='last_name',
        ),
        migrations.AddField(
            model_name='player',
            name='name',
            field=models.CharField(blank=True, default='', max_length=45),
        ),
    ]
